FROM grafana/grafana:latest

# Copy provisioning configurations
COPY provisioning /etc/grafana/provisioning

# Copy sample dashboards
# (Already in provisioning/dashboards if configured that way)
